== AWS SDK for Micronaut

AWS SDK for Micronaut is a successor of https://github.com/agorapulse/grails-aws-sdk[Grails AWS SDK Plugin].
If you are https://github.com/agorapulse/grails-aws-sdk[Grails AWS SDK Plugin] user you should find many of services familiar.

Provided integrations:

* <<CloudWatch Logs>>
* <<DynamoDB>>
* <<Kinesis>>
* <<Lambda>>
* <<Simple Storage Service (S3)>>
* <<Simple Email Service (SES)>>
* <<Simple Notification Service (SNS)>>
* <<Simple Queue Service (SQS)>>
* <<Security Token Service (STS)>>

NOTE: <<Micronaut for API Gateway Proxy>> is handled separately in its own library.

Key concepts of the AWS SDK for Micronaut:

*   Fully leveraging of Micronaut best practises
** Low-level API clients such as `AmazonDynamoDB` available for dependency injection
** Declarative clients and services such as `@KinesisClient` where applicable
** Configuration driven named service beans
** Sensible defaults
** Conditional beans based on presence of classes on the classpath or on the presence of specific properties
* Fully leveraging existing AWS SDK configuration chains (e.g. https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html[default credential provider chain], https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/DefaultAwsRegionProviderChain.html[default region provider chain])
* Strong focus on the ease of testing
** Low-level API clients such as `AmazonDynamoDB` injected by Micronaut and overridable in the tests
** All high-level services hidden behind an interface for easy mocking in the tests
** Declarative clients and services for easy mocking in the tests
* Java-enabled but Groovy is a first-class citizen

In this documentation, the high-level approaches will be discussed first before the lower-level services.

=== Installation

NOTE: For AWS SDK 2.x use artefacts starting with `micronaut-amazon-awssdk`. These artefacts are written pure Java.

NOTE: For AWS SDK 1.x use artefacts starting with `micrnoaut-aws-sdk`. These are considered legacy artefacts and might be removed in the future when the AWS SDK 2.x get wider adoption.

Since  `1.2.8` see the particular subprojects for installation instruction.

include::{includedir}/logs.adoc[]

include::{includedir}/dynamodb.adoc[]

include::{includedir}/kinesis.adoc[]

include::{includedir}/lambda.adoc[]

include::{includedir}/s3.adoc[]

include::{includedir}/ses.adoc[]

include::{includedir}/sns.adoc[]

include::{includedir}/sqs.adoc[]

include::{includedir}/sts.adoc[]

=== Configuration

See the configuration sections for particular services.

Following services support configuring `region` and `endpoint`:

 * CloudWatch
 * DynamoDB
 * Lambda
 * Kinesis
 * S3
 * SES
 * SNS
 * SQS
 * STS

For example, to configure region for DynamoDB you can add following settings:

[source,yaml]
----
aws:
  dynamodb:
    region: us-east-1
    endpoint: http://localhost:8000
----

The same service can also be configured with different https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html[HTTP client] settings when using AWS SDK 2.x.:

[source,yaml]
----
aws:
  dynamodb:
    # can be url-connection or aws-crt, apache is the default
    client: url-connection
    # can be aws-crt, netty is the default
    async-client: aws-crt
----

The client libraries must be added to the classpath. For example for Gradle add the following dependencies:

[source,groovy]
----
dependencies {
    runtimeOnly "software.amazon.awssdk:aws-crt-client:$awsSdk2Version"
    runtimeOnly "software.amazon.awssdk:url-connection-client:$awsSdk2Version"
    runtimeOnly "software.amazon.awssdk:netty-nio-client:$awsSdk2Version"
    runtimeOnly "software.amazon.awssdk:apache-client:$awsSdk2Version"
}
----

The particular client builder can be then configured using `BeanCreatedEventListener` beans:

[source,java,indent=0,options="nowrap"]
.NettyClientCustomizer
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-core/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/core/client/NettyClientCustomizer.java[tags=customizer]
----

