== AWS SDK for Micronaut

AWS SDK for Micronaut is a successor of https://github.com/agorapulse/grails-aws-sdk[Grails AWS SDK Plugin].
If you are https://github.com/agorapulse/grails-aws-sdk[Grails AWS SDK Plugin] user you should find many of services familiar.

Provided integrations:

* <<DynamoDB>>
* <<Kinesis>>
* <<Simple Storage Service (S3)>>
* <<Simple Email Service (SES)>>
* <<Simple Notification Service (SNS)>>
* <<Simple Queue Service (SQS)>>
* <<Security Token Service (STS)>>
* <<WebSockets for API Gateway>>

NOTE: <<Micronaut for API Gateway Proxy>> is handled separately in its own library.

Key concepts of the AWS SDK for Micronaut:

*   Fully leveraging of Micronaut best practises
** Low-level API clients such as `AmazonDynamoDB` available for dependency injection
** Declarative clients and services such as `@KinesisClient` where applicable
** Configuration driven named service beans
** Sensible defaults
** Conditional beans based on presence of classes on the classpath or on the presence of specific properties
* Fully leveraging existing AWS SDK configuration chains (e.g. https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html[default credential provider chain], https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/DefaultAwsRegionProviderChain.html[default region provider chain])
* Strong focus on the ease of testing
** Low-level API clients such as `AmazonDynamoDB` injected by Micronaut and overridable in the tests
** All high-level services hidden behind an interface for easy mocking in the tests
** Declarative clients and services for easy mocking in the tests
* Java-enabled but Groovy is a first-class citizen

In this documentation, the high-level approaches will be discussed first before the lower-level services.

=== Installation

Since  `1.2.8` see the particular subprojects for installation instruction.

Micronaut AWS SDK comes in the three compatibility versions:

* `{project-version}-micronaut-1.2` - for usage with Micronaut `1.2.x` and Grails `4.0.x` (Micronaut `1.0.x` and Micronaut `1.1.x` should also work well with these releases)
* `{project-version}` - for usage with the latest Micronaut  `1.3.x`
* `{project-version}-micronaut-2.0` - for usage with upcoming Micronaut `2.0.x` version

include::{includedir}/dynamodb.adoc[]

include::{includedir}/kinesis.adoc[]

include::{includedir}/s3.adoc[]

include::{includedir}/ses.adoc[]

include::{includedir}/sns.adoc[]

include::{includedir}/sqs.adoc[]

include::{includedir}/sts.adoc[]

include::{includedir}/websockets.adoc[]

=== Configuration

See the configuration sections for particular services.

Following services support configuring `region` and `endpoint`:

 * CloudWatch
 * DynamodDB
 * Kinesis
 * S3
 * SES
 * SNS
 * SQS
 * STS

For example, to configure region for DynamoDB you can add following settings:

```yaml
aws:
  dynamodb:
    region: us-east-1
    endpoint: http://localhost:8000
```

