=== Kinesis

> Amazon Kinesis makes it easy to collect, process, and analyze real-time, streaming data so you can get timely insights and react quickly to new information.

This library provides three approaches to work with Kinesis streams:

1. High-level <<Publishing with `@KinesisClient`>>
2. High-level <<Listening with `@KinesisListener`>>
3. Middle-level <<Kinesis Service>>

==== Installation

[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle (AWS SDK 2.x)
----
// for Kinesis client
annotationProcessor 'com.agorapulse:micronaut-amazon-awssdk-kinesis-annotation-processor:{project-version
implementation 'com.agorapulse:micronaut-amazon-awssdk-kinesis:{project-version}'

// for Kinesis listener
implementation 'com.agorapulse:micronaut-amazon-awssdk-kinesis-worker:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven (AWS SDK 2.x)
----
<!-- for Kinesis client -->
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-kinesis</artifactId>
    <version>{project-version}</version>
</dependency>
<!-- for Kinesis listener -->
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-kinesis-worker</artifactId>
    <version>{project-version}</version>
</dependency>
----

[source,indent=0,role="secondary",subs='verbatim,attributes']
.Gradle (AWS SDK 1.x)
----
// for Kinesis client
annotationProcessor 'com.agorapulse:micronaut-aws-sdk-kinesis-annotation-processor:{project-version}'
implementation 'com.agorapulse:micronaut-aws-sdk-kinesis:{project-version}'
// for Kinesis listener
implementation 'com.agorapulse:micronaut-aws-sdk-kinesis-worker:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven (AWS SDK 1.x)
----
<!-- for Kinesis client -->
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-aws-sdk-kinesis</artifactId>
    <version>{project-version}</version>
</dependency>
<!-- for Kinesis listener -->
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-aws-sdk-kinesis-worker</artifactId>
    <version>{project-version}</version>
</dependency>
----

NOTE: For Kotlin use `kapt` instead of `annotationProcessor` configuration.

==== Configuration

You need no configuration at all but some of the configuration may be useful for you.

[source,yaml,indent=0,options="nowrap"]
.application.yml
----
include::{root-dir}/subprojects/micronaut-aws-sdk-test/src/test/resources/application-docs-kinesis.yml[]
----
<1> You can specify the default stream for https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/aws/kinesis/KinesisService.html[KinesisService] and `@KinesisClient`
<2> You can define multiple configurations
<3> Each of the configuration can be access using `@Named('test') KinesisService` qualifier or you can define the configuration as `value` of `@KinesisClient('test')`
<4> For Kinesis listeners you should provide application name which default to `micronaut.application.name` if not present
<5> You can also provide the of the Kinesis worker
<6> This is the default stream to listen
<7> You can listen to the multiple Kinesis stream by declaring the name of the configuration in the annotation such as `@KinesisListener("other")`


==== Publishing with `@KinesisClient`

If you place `KinesisClient` annotation on the interface then methods
matching predefined pattern will be automatically implemented. Every method of `KinesisClient` puts new records into
the stream.

NOTE: For AWS SDK 2.x, use packages starting `com.agorapulse.micronaut.amazon.awssdk.kinesis`.

NOTE: For AWS SDK 1.x, use packages starting `com.agorapulse.micronaut.aws.sdk.kinesis`.


The following example shows many of available method signatures for publishing records:

[source,java,indent=0,options="nowrap",role="primary"]
.Publishing String Records (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=string]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put String into the stream with generated UUID as partition key
<3> You can user predefined partition key
<4> If the name of the argument does not contain word `parition` then `@PartitionKey` annotation must to be used
<5> You can put String into the stream with predefined partition key and a sequence number
<6> If the name of the sequence number argument does not contain word `sequence` then `@SequenceKey` annotation must to be used
<7> The type of parition key and sequence number does not matter as the value will be always converted to string

[source,java,indent=0,options="nowrap",role="secondary"]
.Publishing String Records (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=string]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put String into the stream with generated UUID as partition key
<3> You can user predefined partition key
<4> If the name of the argument does not contain word `parition` then `@PartitionKey` annotation must to be used
<5> You can put String into the stream with predefined partition key and a sequence number
<6> If the name of the sequence number argument does not contain word `sequence` then `@SequenceKey` annotation must to be used
<7> The type of parition key and sequence number does not matter as the value will be always converted to string

[source,java,indent=0,options="nowrap",role="primary"]
.Publishing Byte Array Records (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=bytes]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put byte array into the stream, UUID as partition key will be generated
<3> If the name of the argument does not contain word `parition` then `@PartitionKey` annotation must to be used
<4> You can put several records wrapped into iterable of `PutRecordsRequestEntry`
<5> You can put several records wrapped into array of `PutRecordsRequestEntry`
<6> If the single argument is of type `PutRecordsRequestEntry` then `PutRecordsResult` object is returned from the method despite only single record has been published

[source,java,indent=0,options="nowrap",role="secondary"]
.Publishing Byte Array Records (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=bytes]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put byte array into the stream, UUID as partition key will be generated
<3> If the name of the argument does not contain word `parition` then `@PartitionKey` annotation must to be used
<4> You can put several records wrapped into iterable of `PutRecordsRequestEntry`
<5> You can put several records wrapped into array of `PutRecordsRequestEntry`
<6> If the single argument is of type `PutRecordsRequestEntry` then `PutRecordsResult` object is returned from the method despite only single record has been published

[source,java,indent=0,options="nowrap",role="primary"]
.Publishing Plain Old Java Objects (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=pogo]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put any object into the stream, UUID as partition key will be generated, the objects will be serialized to JSON
<3> You can put array of any objects into the stream, UUID as partition key will be generated for each record, each object will be serialized to JSON
<4> You can put iterable of any objects into the stream, UUID as partition key will be generated for each record, each object will be serialized to JSON
<5> You can put any object into the stream with predefined partition key, if the name of the argument does not contain word `parition` then `@PartitionKey` annotation must to be used

[source,java,indent=0,options="nowrap",role="secondary"]
.Publishing Plain Old Java Objects (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=pogo]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put any object into the stream, UUID as partition key will be generated, the objects will be serialized to JSON
<3> You can put array of any objects into the stream, UUID as partition key will be generated for each record, each object will be serialized to JSON
<4> You can put iterable of any objects into the stream, UUID as partition key will be generated for each record, each object will be serialized to JSON
<5> You can put any object into the stream with predefined partition key, if the name of the argument does not contain word `parition` then `@PartitionKey` annotation must to be used

[source,java,indent=0,options="nowrap",role="primary"]
.Publishing Events (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/DefaultClient.java[tags=events]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put object implementing `Event` into the stream
<3> You can put iterable of objects implementing `Event` into the stream
<4> You can put array of objects implementing `Event` into the stream
<5> Without any parameters `@KinesisClient` publishes to default stream of the default configuration but you can change it using `@Stream` annotation on the method

[source,java,indent=0,options="nowrap",role="secondary"]
.Publishing Events (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=header]
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/DefaultClient.java[tags=events]
}
----
<1> `@KinesisClient` annotation makes the interface a Kinesis client
<2> You can put object implementing `Event` into the stream
<3> You can put iterable of objects implementing `Event` into the stream
<4> You can put array of objects implementing `Event` into the stream
<5> Without any parameters `@KinesisClient` publishes to default stream of the default configuration but you can change it using `@Stream` annotation on the method


NOTE: The return value of the method is `PutRecordResponse` and `PutRecordsResponse` for AWS SDK 2,x or `PutRecordResult` or `PutRecordsResult` for AWS SDK 1.x, but it can be always omitted and replaced with `void`.

By default, `KinesisClient` publishes records into the default stream defined by `aws.kinesis.stream` property.
You can switch to different configuration by changing the `value` of the annotation such as `@KinesisClient("other")` or
by setting the `stream` property of the annotation such as `@KinesisClient(stream = "MyStream")`. You can change stream
used by particular method using `@Stream` annotation as mentioned above.

==== Listening with `@KinesisListener`

TIP: Before you start implementing your service with `@KinesisListener` you may consider implementing a Lambda function instead.

If you place `KinesisListener` annotation on the method in the bean then the method will be triggered with the new records in the stream.

[source,java,indent=0,options="nowrap",role="primary"]
.Listening to Events (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis-worker/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/worker/KinesisListenerTester.java[tags=all]
----
<1> `@KinesisListener` method must be declared in a bean, e.g. `@Singleton`
<2> You can listen to just plain string records
<3> You can listen to `KinesisClientRecord` objects
<4> You can listen to both string and `KinesisClientRecord` objects
<5> You can listen to objects implementing `Event` interface
<6> You can listen to both `Event` and `KinesisClientRecord` objects
<7> You can listen to any object as long as it can be unmarshalled from the record payload

[source,java,indent=0,options="nowrap",role="secondsary"]
.Listening to Events (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-kinesis-worker/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/worker/KinesisListenerTester.java[tags=all]
----
<1> `@KinesisListener` method must be declared in a bean, e.g. `@Singleton`
<2> You can listen to just plain string records
<3> You can listen to `Record` objects
<4> You can listen to both string and `Record` objects
<5> You can listen to objects implementing `Event` interface
<6> You can listen to both `Event` and `Record` objects
<7> You can listen to any object as long as it can be unmarshalled from the record payload

You can listen to different than default configuration by changing the `value` of the annotation such as `@KinesisListener("other")`.

Multiple methods in a single application can listen to the same configuration (stream). In that case, every method will be executed with the
incoming payload.

==== Kinesis Service

`KinesisService` provides middle-level API for creating, describing, and deleting streams. You can manage shards as well as read records
from particular shards.

Instance of `KinesisService` is created for the default Kinesis configuration and each stream configuration in `aws.kinesis.streams` map.
You should always use `@Named` qualifier when injecting `KinesisService` if you have more than one stream configuration present, e.g. `@Named("other") KinesisService otherService`.

Please, see
https://agorapulse.github.io/micronaut-amazon-awssdk/api/com/agorapulse/micronaut/amazon/awssdk/kinesis/KinesisService.html[KinesisService for AWS SDK 2.x] or
https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/aws/kinesis/KinesisService.html[KinesisService for AWS SDK 1.x]
for the full reference.

==== Testing

You can very easily mock any of the interfaces and declarative services but if you need close-to-production
DynamoDB integration works well with https://www.testcontainers.org/[Testcontainers] and https://localstack.cloud/[LocalStack] using `micronaut-amazon-awssdk-integration-testing` module.

You need to add following dependencies into your build file:


[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle
----
testImplementation 'com.agorapulse:micronaut-amazon-awssdk-integration-testing:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-dynamodb</artifactId>
    <version>{project-version}</version>
</dependency>
----

Then you can set up your tests like this:

[source,groovy,indent=0,role="primary"]
.Groovy
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis/KinesisDemoSpec.groovy[tags=spec]
----
<1> Annotate the specification with `@MicronautTest` to let Micronaut handle the application context lifecycle
<2> Use `@Inject` to let Micronaut inject the beans into your tests

[source,java,indent=0,role="secondary"]
.Java
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/kinesis//KinesisJavaDemoTest.java[tags=spec]
----
<1> Annotate the specification with `@MicronautTest` to let Micronaut handle the application context lifecycle
<2> Use `@Inject` to let Micronaut inject the beans into your tests


[TIP]
====
You can save time creating the new Localstack container by sharing it between the tests.

[source,yaml]
.application-test.yml
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-kinesis/src/test/resources/application-test.yml[]
----
====
