=== Simple Storage Service (S3)

> Amazon Simple Storage Service (Amazon S3) is an object storage service that offers industry-leading scalability, data availability, security, and performance.

This library provides basic support for Amazon S3 using <<Simple Storage Service>>

==== Installation

[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle (AWS SDK 2.x)
----
implementation 'com.agorapulse:micronaut-amazon-awssdk-s3:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven (AWS SDK 2.x)
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-s3</artifactId>
    <version>{project-version}</version>
</dependency>
----

[source,indent=0,role="secondary",subs='verbatim,attributes']
.Gradle (AWS SDK 1.x)
----
implementation 'com.agorapulse:micronaut-aws-sdk-s3:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven (AWS SDK 1.x)
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-aws-sdk-s3</artifactId>
    <version>{project-version}</version>
</dependency>
----

==== Configuration

You can store the name of the bucket in the configuration using `aws.s3.bucket` property. You can create additional configurations
by providing 'aws.s3.buckets' configuration map.


[source,yaml,indent=0,options="nowrap"]
.application.yml
----
include::{root-dir}/subprojects/micronaut-aws-sdk-test/src/test/resources/application-docs-s3.yml[]
----
<1> You can define default bucket for the service
<2> You can define multiple configurations
<3> Each of the configuration can be access using `@Named('test') SimpleStorageService` qualifier

==== Simple Storage Service

`SimpleStorageService` provides middle-level API for managing buckets and uploading and downloading files.

Instance of `SimpleStorageService` is created for the default S3 configuration and each bucket configuration in `aws.s3.buckets` map.
You should always use `@Named` qualifier when injecting `SimpleStorageService` if you have more than one bucket configuration present, e.g. `@Named("test") SimpleStorageService service`.

Following example shows some of the most common use cases for working with S3 buckets.

[source,java,indent=0,options="nowrap"]
.Creating Bucket
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=create-bucket]
----
<1> Create new bucket of given name
<2> The bucket is present within the list of all bucket names

[source,java,indent=0,options="nowrap",role="primary"]
.Upload File (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=store-file]
----
<1> Upload file
<2> File is uploaded
<3> File is present in the summaries of all files

[source,java,indent=0,options="nowrap",role="secondary"]
.Upload File (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-s3/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=store-file]
----
<1> Upload file
<2> File is uploaded
<3> File is present in the summaries of all files

[source,java,indent=0,options="nowrap",role="primary"]
.Upload from `InputStream` (AWS SDK 2.x)
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=store-input-stream]
----
<1> Upload data from stream
<2> Stream is uploaded

[source,java,indent=0,options="nowrap",role="secondary"]
.Upload from `InputStream` (AWS SDK 1.x)
----
include::{root-dir}/subprojects/micronaut-aws-sdk-s3/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=store-input-stream]
----
<1> Upload data from stream
<2> Stream is uploaded

[source,java,indent=0,options="nowrap"]
.Generate URL
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=generate-url]
----
<1> Generate presigned URL
<2> Downloaded content corresponds with the expected content

[source,java,indent=0,options="nowrap"]
.Download File
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=download-file]
----
<1> Prepare a destination file
<2> Download the file locally

[source,java,indent=0,options="nowrap"]
.Delete File
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=delete-file]
----
<1> Delete file
<2> The file is no longer present

[source,java,indent=0,options="nowrap"]
.Delete Bucket
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=delete-bucket]
----
<1> Delete bucket
<2> The Bucket is no longer present

Please, see
https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageService.html[SimpleStorageService AWS SDK 2.x] or
https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/aws/s3/SimpleStorageService.html[SimpleStorageService AWS SDK 1.x] for the full reference.

==== Testing

You can very easily mock any of the interfaces and declarative services but if you need close-to-production
DynamoDB integration works well with https://www.testcontainers.org/[Testcontainers] and https://localstack.cloud/[LocalStack] using `micronaut-amazon-awssdk-integration-testing` module.

You need to add following dependencies into your build file:


[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle
----
implementation 'com.agorapulse:micronaut-amazon-awssdk-integration-testing:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-dynamodb</artifactId>
    <version>{project-version}</version>
</dependency>
----

Then you can set up your tests like this:

[source,groovy,indent=0,role="primary"]
.Groovy
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceSpec.groovy[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceSpec.groovy[tags=setup]

    // test methods

}
----
<1> Annotate the specification with `@MicronautTest` to let Micronaut handle the application context lifecycle
<2> Annotate the specification with `@Property` to set the required Micronaut properties
<3> Use `@Inject` to let Micronaut inject the beans into your tests

[source,java,indent=0,role="secondary"]
.Java
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=header]

include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/s3/SimpleStorageServiceTest.java[tags=setup]

    // test methods

}
----
<1> Annotate the specification with `@MicronautTest` to let Micronaut handle the application context lifecycle
<2> Annotate the specification with `@Property` to set the required Micronaut properties
<3> Use `@Inject` to let Micronaut inject the beans into your tests


[TIP]
====
You can save time creating the new Localstack container by sharing it between the tests.

[source,yaml]
.application-test.yml
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-s3/src/test/resources/application-test.yml[]
----
====
