=== Simple Email Service (SES)

> Amazon Simple Email Service (Amazon SES) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails. It is a reliable, cost-effective service for businesses of all sizes that use email to keep in contact with their customers.

This library provides basic support for Amazon SES using <<Simple Email Service>>

==== Installation

[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle (AWS SDK 2.x)
----
implementation 'com.agorapulse:micronaut-amazon-awssdk-ses:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven (AWS SDK 2.x)
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-ses</artifactId>
    <version>{project-version}</version>
</dependency>
----

[source,indent=0,role="secondary",subs='verbatim,attributes']
.Gradle (AWS SDK 1.x)
----
implementation 'com.agorapulse:micronaut-aws-sdk-ses:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven (AWS SDK 1.x)
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-aws-sdk-ses</artifactId>
    <version>{project-version}</version>
</dependency>
----

==== Simple Email Service

`SimpleEmailService` provides DSL for creating and sending simple emails with attachments. As the other services,
it uses default credentials chain to obtain the credentials.

Following example shows how to send an email with attachment.

[source,groovy,indent=0,options="nowrap",role="primary"]
.Groovy
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-ses/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/ses/SendEmailSpec.groovy[tags=builder]
----
<1> Start building an email
<2> Define subject of the email
<3> Define the from address
<4> Define one or more recipients
<5> Define HTML body (alternatively you can declare plain text body as well)
<6> Define configuration set for the email (https://docs.aws.amazon.com/ses/latest/dg/using-configuration-sets.html)
<7> Define tags for the email, they will be included in SES events
<8> Build an attachment
<9> Define the location of the file to be sent
<10> Define the file name (optional - deduced from the file)
<11> Define the mime type (usually optional - deduced from the file)
<12> Define the description of the file (optional)


[source,java,indent=0,options="nowrap",role="secondary"]
.Java
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-ses/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/ses/SendEmailTest.java[tags=builder]
----
<1> Start building an email
<2> Define subject of the email
<3> Define the from address
<4> Define one or more recipients
<5> Define HTML body (alternatively you can declare plain text body as well)
<6> Define configuration set for the email (https://docs.aws.amazon.com/ses/latest/dg/using-configuration-sets.html)
<7> Define tags for the email, they will be included in SES events
<8> Build an attachment
<9> Define the location of the file to be sent
<10> Define the file name (optional - deduced from the file)
<11> Define the mime type (usually optional - deduced from the file)
<12> Define the description of the file (optional)

Please, see
https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/amazon/awsses/SimpleEmailService.html[SimpleEmailService AWS SDK 2.x]
or
https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/aws/ses/SimpleEmailService.html[SimpleEmailService AWS SDK 1.x]
for the full reference.

==== Testing
It is recommended just to mock the `SimpleEmailService` in your tests as it only contains single abstract method.


