=== Simple Notification Service (SNS)

> Amazon Simple Notification Service (SNS) is a highly available, durable, secure, fully managed pub/sub messaging service that enables you to decouple microservices, distributed systems, and serverless applications.

This library provides two approaches to work with Simple Notification Service topics:

1. High-level <<Publishing with `@NotificationClient`>>
2. Middle-level <<Simple Notification Service>>

==== Installation

[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle
----
annotationProcessor 'com.agorapulse:micronaut-amazon-awssdk-sns-annotation-processor:{project-version}'
implementation 'com.agorapulse:micronaut-amazon-awssdk-sns:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-sns</artifactId>
    <version>{project-version}</version>
</dependency>
----

NOTE: For Kotlin use `kapt` instead of `annotationProcessor` configuration.

==== Configuration
No configuration is required but some of the configuration properties may be useful for you.

[source,yaml,indent=0,options="nowrap"]
.application.yml
----
aws:
  sns:
    topic: TestTopic                              # <1>
    ios:
      arn: 'arn:aws:sns:eu-west-1:123456789:...'  # <2>
    android:
      arn: 'arn:aws:sns:eu-west-1:123456789:...'  # <3>
    amazon:
      arn: 'arn:aws:sns:eu-west-1:123456789:...'  # <4>
    topics:
      test:                                       # <5>
        topic: SomeOtherTopic                     # <6>
----
<1> You can specify the default topic for `SimpleNotificationService` and `@NotificationClient`
<2> Amazon Resource Name for the iOS application mobile push
<3> Amazon Resource Name for the Android application mobile push
<4> Amazon Resource Name for the Amazon application mobile push
<5> You can define multiple configurations
<6> Each of the configuration can be access using `@Named('test') SimpleNotificationService` qualifier or you can define the configuration as `value` of `@NotificationClient('test')`


==== Publishing with `@NotificationClient`

If you place `NotificationClient` annotation on the interface then methods
matching predefined pattern will be automatically implemented. Methods containing word `sms` will send text messages.
Other methods of `NotificationClient` will publish new messages into the topic.

Use packages starting `com.agorapulse.micronaut.amazon.awssdk.sns`.

The following example shows many of available method signatures for publishing records:

[source,java,indent=0,options="nowrap"]
.Publishing String Records
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/DefaultClient.java[lines=18..-1]
----
<1> `@NotificationClient` annotation makes the interface a SNS client
<2> You can specify to which topic is the message published using `@Topic` annotation
<3> You can publish any object which can be converted into JSON.
<4> For FIFO Topics the annotations `@MessageGroupId` and `@MessageDeduplicationId` can be added on method parameters to forward these attributes when publishing
<5> You can add additional subject to published message (only useful for few protocols, e.g. email)
<6> You can publish a string message
<7> You can send SMS using the word `SMS` in the name of the method. One argument must be phone number and its name must contain the word `number`
<8> You can provide additional attributes for the SMS message

NOTE: The return value of the methods is message id returned by AWS.

TIP: You can add `Map<String, String> attributes` argument to send message attributes.

By default, `NotificationClient` publishes messages into the default topic defined by `aws.sns.topic` property.
You can switch to different configuration by changing the `value` of the annotation such as `@NotificationClient("other")` or
by setting the `topic` property of the annotation such as `@NotificationClient(topic = "SomeTopic")`. You can change topic
used by particular method using `@Topic` annotation as mentioned above.

==== Simple Notification Service

`SimpleNotificationService` provides middle-level API for creating, describing, and deleting topics. You can manage applications, endpoints and devices.
You can send messages and notifications.

Instance of `SimpleNotificationService` is created for the default SNS configuration and each topics configuration in `aws.sns.topics` map.
You should always use `@Named` qualifier when injecting `SimpleNotificationService` if you have more than one topic configuration present, e.g. `@Named("other") SimpleNotificationService otherService`.

Following example shows some of the most common use cases for working with Amazon SNS.

===== Working with Topics

[source,java,indent=0,options="nowrap"]
.Creating Topic
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=new-topic]
----
<1> Create new topic of given name
<2> The topic is present within the list of all topics' names


[source,java,indent=0,options="nowrap"]
.Subscribe to Topic
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=subscription]
----
<1> Subscribe to the topic with an email (there are more variants of this method to subscribe to most common protocols such as HTTP(S) endpoints, SQS, ...)
<2> Publish message to the topic
<3> Use the subscription ARN to unsubscribe from the topic

[source,java,indent=0,options="nowrap"]
.Delete Topic
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=delete-topic]
----
<1> Delete the topic
<2> The topic is no longer present within the list of all topics' names

===== Working with Applications

[source,java,indent=0,options="nowrap"]
.Working with Applications
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=applications]
----
<1> Create new Android application (more platforms available)
<2> Register Android device (more platforms available)
<3> Send Android notification (more platforms available)
<4> Validate Android device
<5> Unregister device

===== Sending SMS

[source,java,indent=0,options="nowrap"]
.Sending SMS
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=sms]
----
<1> Send a message to the phone number

Please, see
https://agorapulse.github.io/micronaut-aws-sdk/api/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationService.html[SimpleNotificationService]
for the full reference.

==== Testing

You can very easily mock any of the interfaces and declarative services but if you need close-to-production
DynamoDB integration works well with https://www.testcontainers.org/[Testcontainers] and https://localstack.cloud/[LocalStack] using `micronaut-amazon-awssdk-integration-testing` module.

You need to add following dependencies into your build file:


[source,indent=0,role="primary",subs='verbatim,attributes']
.Gradle
----
testImplementation 'com.agorapulse:micronaut-amazon-awssdk-integration-testing:{project-version}'
----

[source,xml,indent=0,role="secondary",subs='verbatim,attributes']
.Maven
----
<dependency>
    <groupId>com.agorapulse</groupId>
    <artifactId>micronaut-amazon-awssdk-dynamodb</artifactId>
    <version>{project-version}</version>
</dependency>
----

Then you can set up your tests like this:

[source,groovy,indent=0,role="primary"]
.Groovy
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceSpec.groovy[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceSpec.groovy[tags=setup]

    // tests

}
----
<1> Annotate the specification with `@MicronautTest` to let Micronaut handle the application context lifecycle
<2> Annotate the specification with `@Property` to set the required Micronaut properties
<3> Use `@Inject` to let Micronaut inject the beans into your tests

[source,java,indent=0,role="secondary"]
.Java
----
class SimpleNotificationServiceTest {

include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=header]
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/groovy/com/agorapulse/micronaut/amazon/awssdk/sns/SimpleNotificationServiceTest.java[tags=setup]

    // tests

}
----
<1> Annotate the specification with `@MicronautTest` to let Micronaut handle the application context lifecycle
<2> Annotate the specification with `@Property` to set the required Micronaut properties
<3> Use `@Inject` to let Micronaut inject the beans into your tests


[TIP]
====
You can save time creating the new Localstack container by sharing it between the tests.

[source,yaml]
.application-test.yml
----
include::{root-dir}/subprojects/micronaut-amazon-awssdk-sns/src/test/resources/application-test.yml[]
----
====

