/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2018-2026 Agorapulse.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
plugins {
    id 'com.agorapulse.gradle.root-project'
}

if (!project.hasProperty('mavenCentralUsername'))       ext.mavenCentralUsername       = System.getenv('MAVEN_CENTRAL_USERNAME') ?: '**UNDEFINED**'
if (!project.hasProperty('mavenCentralPassword'))       ext.mavenCentralPassword       = System.getenv('MAVEN_CENTRAL_PASSWORD') ?: '**UNDEFINED**'
if (!project.hasProperty('signingInMemoryKeyId'))       ext.signingInMemoryKeyId       = System.getenv('SIGNING_KEY_ID') ?: '**UNDEFINED**'
if (!project.hasProperty('signingInMemoryKeyPassword')) ext.signingInMemoryKeyPassword = System.getenv('SIGNING_PASSWORD') ?: '**UNDEFINED**'
if (!project.hasProperty('signingInMemoryKey'))         ext.signingInMemoryKey         = System.getenv('SIGNING_SECRET_KEY_PATH') ? rootProject.file(System.getenv('SIGNING_SECRET_KEY_PATH')).text : '**UNDEFINED**'

allprojects {
    repositories {
        mavenCentral()
        maven { url 'https://repo.spring.io/release' }
    }
}

gradleProjects {
    subprojects {
        dirs(['subprojects', 'kotlin-libs', 'benchmarks']) {
            java {
                toolchain {
                    languageVersion = JavaLanguageVersion.of(javaVersion as int)
                }
            }

            micronaut {
                if (project.hasProperty('importMicronautPlatform')) {
                    importMicronautPlatform = true
                }
                testRuntime 'spock'
                processing {
                    incremental false
                }
            }
        }

        dirs(['subprojects', 'platforms', 'kotlin-libs']) {
            mavenPublishing {
                publishToMavenCentral(true)
                signAllPublications()

                pom {
                    name = project.name
                    description = 'Micronaut AWS SDK'
                    inceptionYear = '2018'
                    url = "https://github.com/${rootProject.slug}"
                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                            distribution = 'repo'
                        }
                    }
                    developers {
                        developer {
                            id = 'musketyr'
                            name = 'Vladimir Orany'
                            url = 'https://github.com/musketyr/'
                        }
                    }
                    scm {
                        url = "https://github.com/${rootProject.slug}"
                        connection = "scm:git:https://github.com/${rootProject.slug}.git"
                        developerConnection = "scm:git:git@github.com:${rootProject.slug}.git"
                    }
                    issueManagement {
                        system = 'GitHub'
                        url = "https://github.com/${rootProject.slug}/issues"
                    }
                }
            }

            signing {
                useInMemoryPgpKeys(rootProject.ext.signingInMemoryKey, rootProject.ext.signingInMemoryKeyPassword)
                sign publishing.publications
            }
        }

        dirs(['subprojects', 'benchmarks']) {
            dependencies {
                api platform(project(':micronaut-aws-sdk-dependencies'))

                compileOnly "org.apache.groovy:groovy:$groovyVersion"
                compileOnly 'io.micronaut.aws:micronaut-aws-sdk-v2'
                testImplementation "org.apache.groovy:groovy:$groovyVersion"
                testImplementation 'io.micronaut.aws:micronaut-aws-sdk-v2'

                implementation 'io.micronaut:micronaut-inject'
                implementation 'io.micronaut:micronaut-runtime'

                testAnnotationProcessor 'io.micronaut:micronaut-inject-java'

                testImplementation 'io.micronaut:micronaut-inject-groovy'

                testImplementation "org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion"
                testImplementation "org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion"

                testImplementation 'io.micronaut.test:micronaut-test-junit5'
                testImplementation 'io.micronaut.test:micronaut-test-spock'
                testImplementation "org.spockframework:spock-core:$spockVersion"

                testRuntimeOnly 'ch.qos.logback:logback-classic:1.2.3'
                testRuntimeOnly 'org.yaml:snakeyaml'
            }

            compileJava.options.compilerArgs += '-parameters'
            compileTestJava.options.compilerArgs += '-parameters'

            test {
                useJUnitPlatform()
                environment 'AWS_CBOR_DISABLE', 'true'
                systemProperty 'TEST_RESOURCES_FOLDER', new File(projectDir, 'src/test/resources').canonicalPath
                systemProperty 'user.timezone', 'UTC'
                systemProperty 'user.language', 'en'
            }

            tasks.register('cleanOut', Delete) {
                delete file('out')
            }
            clean.dependsOn cleanOut
        }

        dirs(['subprojects', 'kotlin-libs']) {
            rootProject.project(':micronaut-aws-sdk-bom').dependencies.constraints.api project
        }
    }
}
