#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2018-2026 Agorapulse.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

org.gradle.caching=true

slug=agorapulse/micronaut-aws-sdk
group=com.agorapulse

javaVersion = 25

agorapulseGradlePluginsVersion = 4.4.3
mavenCentralPublishPluginVersion = 0.34.0
develocityPluginVersion = 4.2.2
gitPublishPluginVersion = 2.1.3

micronautVersion = 5.0.0
micronautGradlePluginVersion = 5.0.0

gruVersion = 2.2.0
awsSdk2Version = 2.41.16
awsLambdaRuntimeVersion=2.5.0
awsLambdaEventsVersion=3.16.1
testcontainersVersion = 1.21.4
ministackVersion = 0.1.5
closureSupportVersion=0.6.3
mockitoVersion=5.23.0
kotlinVersion=2.3.21
kspVersion=2.3.7
grgitVersion=5.0.0
opencsvVersion=5.12.0
junitJupiterVersion=6.0.3
spockVersion=2.4-groovy-5.0

# other versions creates conflicts in Groovydoc
groovyVersion = 5.0.0

# this should be aligned to Micronaut version
# required for AWS CBOR marshalling
jackson.datatype.version=3.0.0

# kinesis client version
kinesisClientV2Version=2.7.2

# google auth library version
googleAuthVersion=1.23.0

# project reactor version
projectReactorVersion = 3.8.2

# awaitility version
awaitilityVersion = 4.2.0
