/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2018-2026 Agorapulse.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://agorapulse.jfrog.io/agorapulse/gradle-plugins-releases-local/' }
        mavenCentral()
    }
    plugins {
        id 'com.agorapulse.gradle.micronaut-library'           version "${agorapulseGradlePluginsVersion}"
        id 'com.agorapulse.gradle.groovy-common-configuration' version "${agorapulseGradlePluginsVersion}"
        id 'com.agorapulse.gradle.guide'                       version "${agorapulseGradlePluginsVersion}"
        id 'com.vanniktech.maven.publish'                      version "${mavenCentralPublishPluginVersion}"
        id 'org.jetbrains.kotlin.jvm'                          version "${kotlinVersion}"
        id 'org.jetbrains.kotlin.plugin.allopen'               version "${kotlinVersion}"
        id 'com.google.devtools.ksp'                           version "${kspVersion}"
    }
}

buildscript {
    repositories {
        gradlePluginPortal()
        maven { url 'https://agorapulse.jfrog.io/agorapulse/gradle-plugins-releases-local/' }
        mavenCentral()
    }
    dependencies {
        classpath "io.micronaut.gradle:micronaut-minimal-plugin:$micronautGradlePluginVersion"
        classpath "com.agorapulse.gradle:micronaut-library:$agorapulseGradlePluginsVersion"
        classpath "com.agorapulse.gradle:groovy-common-configuration:$agorapulseGradlePluginsVersion"
        classpath "com.vanniktech:gradle-maven-publish-plugin:$mavenCentralPublishPluginVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "org.jetbrains.kotlin.plugin.allopen:org.jetbrains.kotlin.plugin.allopen.gradle.plugin:$kotlinVersion"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$kspVersion"
    }
}

plugins {
    id 'com.agorapulse.gradle.settings' version "${agorapulseGradlePluginsVersion}"
    id 'com.gradle.develocity'          version "${develocityPluginVersion}"
}

develocity {
    buildScan {
        termsOfUseUrl = 'https://gradle.com/terms-of-service'
        termsOfUseAgree = 'yes'
        publishing.onlyIf { true }
    }
}

gradleProjects {
    directories = ['subprojects', 'platforms', 'kotlin-libs', 'benchmarks', 'examples', 'docs']

    plugins {
        dir('subprojects') {
            id 'groovy'
            id 'java-library'
            id 'com.agorapulse.gradle.micronaut-library'
            id 'com.agorapulse.gradle.groovy-common-configuration'
            id 'com.vanniktech.maven.publish'
        }
        dir('platforms') {
            id 'java-platform'
            id 'com.vanniktech.maven.publish'
        }
        dir('kotlin-libs') {
            id 'com.agorapulse.gradle.micronaut-library'
            id 'com.vanniktech.maven.publish'
        }
        dir('benchmarks') {
            id 'com.agorapulse.gradle.micronaut-library'
        }
    }
}

rootProject.name = 'micronaut-aws-sdk'
