=== Simple Storage Service (S3)

> Amazon Simple Storage Service (Amazon S3) is an object storage service that offers industry-leading scalability, data availability, security, and performance.

This library provides basic support for Amazon S3 using <<Simple Storage Service>>

==== Configuration

You can store the name of the bucket in the configuration using `aws.s3.bucket` property. You can create additional configurations
by providing 'aws.s3.buckets' configuration map.


[source,yaml,indent=0,options="nowrap"]
.application.yml
----
include::../subprojects/micronaut-aws-sdk/src/test/resources/application-docs-s3.yml[]
----
<1> You can define default bucket for the service
<2> You can define multiple configurations
<3> Each of the configuration can be access using `@Named('test') SimpleStorageService` qualifier

==== Simple Storage Service

`SimpleStorageService` provides middle-level API for managing buckets and uploading and downloading files.

Instance of `SimpleStorageService` is created for the default S3 configuration and each bucket configuration in `aws.s3.buckets` map.
You should always use `@Named` qualifier when injecting `SimpleStorageService` if you have more than one bucket configuration present, e.g. `@Named("test") SimpleStorageService service`.

Following example shows some of the most common use cases for working with S3 buckets.

[source,java,indent=0,options="nowrap"]
.Creating Bucket
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=create-bucket]
----
<1> Create new bucket of given name
<2> The bucket is present within the list of all bucket names

[source,java,indent=0,options="nowrap"]
.Upload File
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=store-file]
----
<1> Upload file
<2> File is uploaded
<3> File is present in the summaries of all files

[source,java,indent=0,options="nowrap"]
.Upload from `InputStream`
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=store-input-stream]
----
<1> Upload data from stream
<2> Stream is uploaded

[source,java,indent=0,options="nowrap"]
.Generate URL
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=generate-url]
----
<1> Generate presigned URL
<2> Downloaded content corresponds with the expected content

[source,java,indent=0,options="nowrap"]
.Download File
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=download-file]
----
<1> Prepare a destination file
<2> Download the file locally

[source,java,indent=0,options="nowrap"]
.Delete File
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=delete-file]
----
<1> Delete file
<2> The file is no longer present

[source,java,indent=0,options="nowrap"]
.Delete Bucket
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=delete-bucket]
----
<1> Delete bucket
<2> The Bucket is no longer present

Please, see https://agorapulse.github.io/micronaut-libraries/docs/javadoc/micronaut-aws-sdk/com/agorapulse/micronaut/aws/s3/SimpleStorageService.html[SimpleStorageService] for the full reference.

==== Testing
You can very easily mock the `SimpleStorageService` but if you need close-to-production
S3 integration works well with https://www.testcontainers.org/[Testcontainers] and https://localstack.cloud/[LocalStack].

You need to add following dependencies into your build file:

[source,indent=0,role="primary"]
.Gradle
----
compile group: 'org.testcontainers', name: 'localstack', version: '1.10.2'
compile group: 'org.testcontainers', name: 'spock', version: '1.10.2'
----

[source,xml,indent=0,role="secondary"]
.Maven
----
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>localstack</artifactId>
    <version>1.10.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>spock</artifactId>
    <version>1.10.2</version>
    <scope>test</scope>
</dependency>

----

Then you can setup your tests like this:

[source,groovy,indent=0,role="primary"]
.Groovy
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceSpec.groovy[tags=header]

include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceSpec.groovy[tags=setup]

    // test methods

}
----
<1> Annotate the specification with `@Testcontainers` to let Spock manage the Testcontainers for you
<2> Prepare the reference to the `ApplicationContext`, `@AutoCleanup` guarantees closing the context after the tests
<3> Create an instance of `LocalStackContainer` with S3 support enabled
<4> Create `AmazonS3` client using the LocalStack configuration
<5> Set the default bucket
<6> Register `AmazonS3` service running against LocalStack
<7> You can obtain instance of `SimpleStorageService` from the context

[source,java,indent=0,role="secondary"]
.Java
----
include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=header]

include::../subprojects/micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/s3/SimpleStorageServiceTest.java[tags=setup]

    // test methods

}
----
<1> Create an instance of `LocalStackContainer` with Kinesis and  DynamoDB (required by the listener) support enabled
<2> Prepare the reference to the `ApplicationContext`
<3> Create `AmazonS3` client using the LocalStack configuration
<4> Register `AmazonS3` service running against LocalStack
<5> Don't forget to close `ApplicationContext`


