=== S3

> Amazon Simple Storage Service (Amazon S3) is an object storage service that offers industry-leading scalability, data availability, security, and performance.

This library provides basic support for Amazon S3 using <<Simple Storage Service>>

==== Configuration

You can store the name of the bucket in the configuration using `aws.s3.bucket` property. You can create additional configurations
by providing 'aws.s3.buckets' configuration map.


[source,yaml,indent=0,options="nowrap"]
.application.yml
----
include::../micronaut-aws-sdk/src/test/resources/application-docs-s3.yml[]
----
<1> You can specify the default stream for https://agorapulse.github.io/micronaut-libraries/docs/javadoc/micronaut-aws-sdk/com/agorapulse/micronaut/aws/kinesis/KinesisService.html[KinesisService] and `@KinesisClient`
<2> You can define multiple configurations
<3> Each of the configuration can be access using `@Named('test') KinesisService` qualifier or you can define the configuration as `value` of `@KinesisClient('test')`
<4> Application name is required for `@KinesisListner`
<5> Optional id of the Kinesis worker (listener)
<6> Stream to listen is required for `@KinesisListener`
<7> You can define multiple listeners configurations
<8> The name of the configuration will be used as `value` of `@KinesisListener('test')`


==== Simple Storage Service

`KinesisService` provides middle-level API for creating, describing, and deleting streams. You can manage shards as well as read records
from particular shards.

Instance of `KinesisService` is created for the default Kinesis configuration and each stream configuration in `aws.kinesis.streams` map.
You should always use `@Named` qualifier when injecting `KinesisService` if you have more than one stream configuration present, e.g. `@Named("other") KinesisService otherService`.

Please, see https://agorapulse.github.io/micronaut-libraries/docs/javadoc/micronaut-aws-sdk/com/agorapulse/micronaut/aws/s3/SimpleStorageService.html[SimpleStorageService] for the full reference.

==== Testing
You can very easily mock any of the interfaces and declarative services but if you need close-to-production
Kinesis integration works well with https://www.testcontainers.org/[Testcontainers] and https://localstack.cloud/[LocalStack].

You need to add following dependencies into your build file:

[source,indent=0,role="primary"]
.Gradle
----
compile group: 'org.testcontainers', name: 'localstack', version: '1.10.2'
compile group: 'org.testcontainers', name: 'spock', version: '1.10.2'
----

[source,xml,indent=0,role="secondary"]
.Maven
----
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>localstack</artifactId>
    <version>1.10.2</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>spock</artifactId>
    <version>1.10.2</version>
    <scope>test</scope>
</dependency>

----

Then you can setup your tests like this:

[source,groovy,indent=0,role="primary"]
.Groovy
----
include::../micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/KinesisAnnotationsSpec.groovy[tags=testcontainers-header]

include::../micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/KinesisAnnotationsSpec.groovy[tags=testcontainers-setup]

include::../micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/KinesisAnnotationsSpec.groovy[tags=testcontainers-test]

}
----
<1> Annotate the specification with `@Testcontainers` to let Spock manage the Testcontainers for you
<2> `@RestoreSystemProperties` will guarantee that system properties will be restore after the test
<3> Create an instance of `LocalStackContainer` with Kinesis and  DynamoDB (required by the listener) support enabled
<4> Prepare the reference to the `ApplicationContext`, `@AutoCleanup` guarantees closing the context after the tests
<5> Disable CBOR protocol for Kinesis (not supported by LocalStack/Kinesilite)
<6> Create `AmazonDynamoDB` client using the LocalStack configuration
<7> Create `AmazonKinesis` client using the LocalStack configuration
<8> Prepare the application context with required properties and service LocalStack
<9> You can obtain instance of `KinesisService` from the context
<10> You can obtain instance of declarative listener from the context
<11> You can obtain instance of declarative client from the context

[source,java,indent=0,role="secondary"]
.Java
----
include::../micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/KinesisTest.java[tags=testcontainers-header]

include::../micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/KinesisTest.java[tags=testcontainers-setup]

include::../micronaut-aws-sdk/src/test/groovy/com/agorapulse/micronaut/aws/kinesis/KinesisTest.java[tags=testcontainers-test]

}
----
<1> Prepare the reference to the `ApplicationContext`
<2> Create an instance of `LocalStackContainer` with Kinesis and  DynamoDB (required by the listener) support enabled
<3> Disable CBOR protocol for Kinesis (not supported by LocalStack/Kinesilite)
<4> Create `AmazonDynamoDB` client using the LocalStack configuration
<5> Create `AmazonKinesis` client using the LocalStack configuration
<6> Prepare required properties
<7> Prepare the application context with required properties and service LocalStack
<8> Reset CBOR protocol settings after the test
<9> Close the application context after the test
<10> You can obtain instance of `KinesisService` from the context
<11> You can obtain instance of declarative listener from the context
<12> You can obtain instance of declarative client from the context


