name: Gradle RC Watchdog

on:
  schedule:
    - cron:  '0 0 13 * *'

jobs:
  check:
    name: Verify the Latest Gradle Version
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true

    steps:
    - uses: actions/checkout@v1

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        cache: gradle
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: check --parallel
        gradle-version: rc
