name: Gradle RC Watchdog

on:
  schedule:
    - cron:  '0 0 13 * *'

jobs:
  check:
    name: Verify the Latest Gradle Version
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
      CI: true

    steps:
    - uses: actions/checkout@v1

    - name: Setup Java 8
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 8
        cache: gradle
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: check --stacktrace
        gradle-version: rc
